### ISSUE TITLE
Basic docs for this?

### ISSUE THREAD

**Issue by wyattbenno777** [ActiveCampaign/activecampaign-api-nodejs#40]
I am trying to get a list of contacts from AC.

`var contact_list = ac.api("contact/list", {});
  contact_list.then(function(result) {
    // successful request
    console.log(result);
  }, function(result) {
    // request error
  });`

This returns nothing even though contacts are associated with the account.

`{ result_code: 0,
  result_message: 'Failed: Nothing is returned',
  result_output: 'json',
  success: 0,
  error: 'Failed: Nothing is returned' }`

How do I use this to return results?

**Comment by ac-pevans** [comment]
@wyattbenno777 I think you're going to need to change your resource from `contact/list` to `contact/list?ids=ALL` (which goes into the first parameter there because `ids` is a GET parameter, and the second object parameter in `ac.api()` is reserved for POST data).

For reference, check out the base documentation for the API call this is using, [contact_list](http://www.activecampaign.com/api/example.php?call=contact_list).
