### ISSUE TITLE
Ids all is no longer working

### ISSUE THREAD

**Issue by wyattbenno777** [ActiveCampaign/activecampaign-api-nodejs#41]
`var contacts_get = ac.api("contact/list?ids=all", {});
        contacts_get.then(function(result) {
            // successful request
            console.log("result is ", result);
        }, function(result) {
            // request error
        });`

Ids all is no longer working, this returns an empty object.

**Comment by cristiangrama** [comment]
@wyattbenno777 Can you provide the full response?

**Comment by wyattbenno777** [comment]
Hi. I tried this again.

This is the JSON response. For this url.

https://ours.api-us1.com/admin/api.php?api_key=our_key&api_action=contact_list&api_output=json&ids=all

With id it does work with ids=all it does not.

result_code | 0
result_message | "Failed: Nothing is returned"
result_output | "json"

**Comment by mthommes** [comment]
Hello! The `contact_list` method will only return contacts that are associated with at least one list. Can you confirm that the missing contacts in your response already meet that criteria? In other words, since no contacts are returned I would suspect that you have no contacts that are associated with at least one list. If that's not the issue, then we can escalate this issue further. Thank you!

**Comment by wyattbenno777** [comment]
@mthommes That did it. Thank you!
